### ISSUE TITLE
SCP-268 is a cause of overdose

### ISSUE THREAD

**Issue by coco9515** [steven4547466/Overdose#1]
As the title state, using SCP-268 can cause an overdose.
I just try it, 4 uses of this SCP without using anything else and I got an overdose. 

My config of this plugin : 
```yml
Overdose:
  is_enabled: true
  # Sets the min uses before possible chance of getting poisoned (It's impossible to be poisoned before this number). Must be greater than 1.
  min_uses: 2
  # Sets the initial starting chance of getting poisoned. 0-100
  base_chance: 45
  # Sets whether the chance increase is exponential or not (Exponential meaning BaseChance^(Medical items used - MinUses)).
  chance_increase_exponential: true
  # Sets the amount of increase each use (Medical item used - MinUses). Disregarded if exponential.
  chance_increase_per: 15
  # Sets the amount of health to drain per second.
  health_drain_per_second: 1.25
  # Sets the amount of increase to health drain on multiple poison.
  health_drain_per_second_increase: 1.5
  # Sets whether this plugin works on painkillers.
  painkiller_enabled: true
  # Sets whether this plugin works on adrenaline.
  adrenaline_enabled: true
  # Sets whether this plugin works on medkits.
  med_kit_enabled: false
  # Sets whether this plugin works on SCP-207.
  s_c_p207_enabled: false
  # Sets whether SCP-500 cleanses the effect.
  can_be_cleansed: true
  # Sets the message the player sees when they begin to drain health.
  overdose_message: Tu as pris trop de médicaments, tu fais une <color=red>overdose</color>
  # Show debug messages?
  debug: false
```
